id: "nola"
name: "No Lag"
description: "Destroys the lag in the minecraft world with over 6 different and adjustable methods. "
author: "2mal3"
version: "v3.1.4"
minecraft: "1.20"

output: "build"

data_pack:
  name: "No-Lag"
  description: "v3.1.4"
  load:
    - "src"
    - pack.png: "pack.png"


pipeline:
  - beet.contrib.rename_files
  - mecha
  - plugins.remove_empty_functions
  - plugins.installation_advancement
require:
  - bolt

meta:
  version: 30104

  bolt:
    entrypoint:
      - ""

  rename_files:
    data_pack:
      match:
        functions: "nola:*"
      find: '((?!.*-).+)'
      replace: '\1/child'

  installation_advancement:
    icon:
      item: "minecraft:clock"
